volumes:
  mysql-data:
    driver: local

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salus
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  foodloader:
    build: ./DE
    depends_on:
      - mysql
    volumes:
      - ./DE/food_data.csv:/app/food_data.csv

