volumes:
  mysql-data:
    driver: local

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salus
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-server:
    build: ./spring-server
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      AI_HOST: ai-model
    ports:
      - "8085:8080"

  food-loader:
    build:
      context: ./DE
      dockerfile: load/Dockerfile
    depends_on:
      - mysql
    env_file:
      - ./DE/load/.env
    
